apiVersion: v1
kind: Service
metadata:
  name: cjdbc-service
spec:
  ports:
  - name: cjdbc-svc
    port: 25322 
    targetPort: 25322
    nodePort: 31112
  selector:
    app: cjdbc
  type: NodePort

