apiVersion: v1
kind: Service
metadata:
  name: tomcat-service
spec:
  ports:
  - name: tomcat-svc
    port: 8080
    targetPort: 8080
    nodePort: 31111
  - name: mod-jk
    port: 8009
    targetPort: 8009
    nodePort: 31113
    #protocol: AJP
  selector:
    app: tomcat
  type: NodePort

