apiVersion: v1
kind: ReplicationController
metadata:
  name: cjdbc-controller
spec:
  replicas: 1
  selector:
    app: cjdbc
  template:
    metadata:
      labels:
        app: cjdbc
    spec:
      containers:
        - image: myregistry.local:5000/ubuntu:latest
          name: cjdbc
          resources:
            limits:
              cpu: "0.25"
              memory: 2Gi
          ports:
          - containerPort: 80
          volumeMounts:
            - name: timezone
              mountPath: /etc/localtime
            #- name: httpd-conf
            #  mountPath: /usr/local/apache2/conf
      nodeSelector:
          diskspeed: slow
      volumes:
        - name: timezone
          hostPath:
            path: /usr/share/zoneinfo/America/New_York
        #- name: httpd-conf
        #  hostPath:
        #    path: /tmp/httpd-conf
        #    type: Directory
