apiVersion: v1
kind: ReplicationController
metadata:
  name: rubbos-client-controller
spec:
  replicas: 1
  selector:
     app: rubbos-client
  template:
     metadata:
       labels:
         app: rubbos-client
     spec:
       containers:
       #- image: myregistry.local:5000/rubbos-client:latest
       - image: wuqingzcp/rubbos-webapp:rubbos-client
         name: rubbos-client
         #resources:
         #  limits:
         #    cpu: "0.7"
         #    memory: 1Gi
         volumeMounts:
           - name: timezone
             mountPath: /etc/localtime
           - name: rubbos-client
             mountPath: /tmp/RUBBoS
       nodeSelector:
       #  diskspeed: slow
         diskspeed: client
       volumes:
         - name: timezone
           hostPath:
             path: /usr/share/zoneinfo/America/New_York
         - name: rubbos-client
           hostPath:
             path: /tmp/RUBBoS-Client-current
